name: DID BTC1 JS - Push Workflow

on: [push]

jobs:
  lint-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: Install dependencies
        run: pnpm install -r --no-lockfile
      
      - name: Run linter for all packages
        run: pnpm lint

      - name: Build all packages, tests and docs
        run: pnpm build:all
      
      - name: Run tests
        run: pnpm test
      
      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v4.0.1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     slug: jintekc/did-btc1-js